Repository sainirock61/Discrete-Structure, pull requests merged in 2021-10, with the labels that each got.

#6 Update P20.CPP
  P20.CPP
Labels: hacktoberfest-accepted

#4 Update P9.CPP
  P9.CPP
Labels: hacktoberfest-accepted

#3 Reverse Triangle Added
  P15.CPP
Labels: hacktoberfest-accepted

#2 Update P17.CPP
  P17.CPP
Labels: hacktoberfest-accepted

#1 Update P1.CPP
  P1.CPP
Labels: hacktoberfest-accepted

#11 Update P16.CPP
  P16.CPP
Labels: good first issue, hacktoberfest-accepted

#10 Update P13.CPP
  P13.CPP
Labels: enhancement, good first issue, hacktoberfest-accepted

#9 Update P8.CPP
  P8.CPP
Labels: good first issue, hacktoberfest-accepted

#8 Update P6.CPP
  P6.CPP
Labels: enhancement, hacktoberfest-accepted

#7 Update P5.CPP
  P5.CPP
Labels: enhancement, hacktoberfest-accepted

#12 Create TowerOfHanoi_CPP
  TowerOfHanoi_CPP
Labels: hacktoberfest-accepted

#14 Update P7.CPP
  P7.CPP
Labels: good first issue, hacktoberfest-accepted

#13 Update P2.CPP
  P2.CPP
Labels: good first issue, hacktoberfest-accepted

#19 Update P20.CPP
  P20.CPP
Labels: help wanted, hacktoberfest-accepted

#18 Update P11.CPP
  P11.CPP
Labels: help wanted, hacktoberfest-accepted

#17 Update P19.CPP
  P19.CPP
Labels: enhancement, help wanted, hacktoberfest-accepted

#16 Update P(3)(4).CPP
  P(3)(4).CPP
Labels: enhancement, help wanted, hacktoberfest-accepted

#15 Update P17.CPP
  P17.CPP
Labels: help wanted, hacktoberfest-accepted
