Repository sainirock61/Discrete-Structure, pull requests merged in 2022-10, with the labels that each got.

#23 Threaded Binary Tree
  P5.CPP
Labels: hacktoberfest-accepted

#22 Update P19.CPP
  P19.CPP
Labels: hacktoberfest-accepted

#21 Update P2.CPP
  P2.CPP
Labels: help wanted, good first issue, hacktoberfest-accepted

#20 Update TowerOfHanoi_CPP
  TowerOfHanoi_CPP
Labels: enhancement, help wanted, hacktoberfest-accepted

#28 Next Greater Frequency Element
  P8.CPP
Labels: hacktoberfest-accepted

#27 Find cubic root of a number
  P7.CPP
Labels: hacktoberfest-accepted

#26 Inorder predecessor and successor
  P16.CPP
Labels: hacktoberfest-accepted

#25 Floor and Ceil from a BST
  P19.CPP
Labels: hacktoberfest-accepted

#29 Level Order Traversal of a Binary tree
  LevelOrderTraversal.cpp
Labels: enhancement, hacktoberfest-accepted

#33 Update TowerOfHanoi_CPP
  TowerOfHanoi_CPP
Labels: enhancement, hacktoberfest-accepted

#32 Create Aho-Corasick.cpp
  Aho-Corasick.cpp
Labels: enhancement, hacktoberfest-accepted

#31 Create Rabin-Karp.cpp
  Rabin-Karp.cpp
Labels: enhancement, hacktoberfest-accepted

#30 Update P9.CPP
  P9.CPP
Labels: enhancement, hacktoberfest-accepted
